# Starter pipeline
trigger:
- main

pool:
  vmImage: window-latest

steps:

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $tokenUrl = "https://login.microsoftonline.com/common/oauth2/token"
      $tokenBody = @ {
      grant_type = "password"
      client_id = "$(CLIENTID)"
      client_secret = "$(CLIENTSECRET)"
      resource = "https://lcsapi.lcs.dynamics.com"
      username = "$(USERNAME)"
      password = "$(PASSWORD)"
      }
      $tokenResponse = Invoke - RestMethod - Method 'POST' - Uri $tokenUrl -Body $tokenBody
      $token = $tokenResponse .access_token
      Write-Host $token
      Write-Host "##vso[task.setvariable variable=TOKENOUT;isOutput=true]$token"
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
